version: "3"

services:

  app:
    container_name: app
    build: ./app
    restart: always
    healthcheck:
      test: curl --fail localhost/health || exit 1
      interval: 10s
      retries: 3
      timeout: 10s

  grafana:
    container_name: grafana
    image: grafana/grafana
    restart: always
    volumes:
      - grafana-data:/var/lib/grafana
      - ./monitoring/grafana.ini:/etc/grafana/grafana.ini
    links:
      - prometheus
    ports:
      - 3000:3000
    depends_on:
      - prometheus
    env_file:
      - .env
    healthcheck:
      test: curl --fail 130.193.51.98:3000 || exit 1
      interval: 10s
      retries: 3
      timeout: 10s

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    links:
      - node-exporter
      - app
    volumes:
      - prom-data:/prometheus
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml


  node-exporter:
    container_name: node-exporter
    image: prom/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude'
      - '^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)'

volumes:
  grafana-data:
  prom-data:
